services:
  - type: web
    name: my-django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn myproject.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false  # Это означает, что ключ нужно добавить вручную в Render
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString

databases:
  - name: my-database
    plan: free
