# Generated by Django 5.1.3 on 2024-11-25 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_body_task_title_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
