# Generated by Django 5.1.3 on 2024-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(verbose_name="default=datetime=now"),
        ),
    ]
