# Generated by Django 5.1.3 on 2024-11-26 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_task_completed_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 23, 59)),
        ),
    ]
