# Generated by Django 5.1.3 on 2024-11-27 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 28, 17, 33, 52, 565077)
            ),
        ),
    ]
