# Generated by Django 5.1.3 on 2024-11-30 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_task_deadline_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("FRIEND", "Friend"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend Request"),
                    ("message", "Message"),
                    ("task_deadline", "Task Deadline"),
                    ("friend_request_accepted", "Friend Request Accepted"),
                    ("friend_request_rejected", "Friend Request Rejected"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 1, 17, 58, 57, 638605)
            ),
        ),
    ]
