# Generated by Django 5.1.3 on 2024-12-01 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_educationalcontent_alter_task_deadline_pomodorotimer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 17, 39, 1, 874670)
            ),
        ),
    ]
