# Generated by Django 5.1.3 on 2024-12-02 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_task_deadline_consumedcalories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 3, 16, 2, 43, 563671)
            ),
        ),
    ]
