# Generated by Django 5.1.3 on 2025-03-06 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_achievement_rename_points_profile_exp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 7, 16, 27, 32, 270678)
            ),
        ),
    ]
