# Generated by Django 5.1.3 on 2025-03-09 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_task_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pomodorotimer",
            old_name="start_time",
            new_name="start_timer",
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 10, 17, 39, 45, 460880)
            ),
        ),
    ]
