# Generated by Django 5.1.3 on 2025-03-13 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_friendship_friend_alter_group_members_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNutritionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories_goal", models.FloatField(default=2000)),
                ("protein_goal", models.FloatField(default=50)),
                ("fat_goal", models.FloatField(default=70)),
                ("carbs_goal", models.FloatField(default=260)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
