# Generated by Django 5.1.3 on 2025-03-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_usernutritiongoal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumedcalories",
            old_name="fat",
            new_name="fats",
        ),
        migrations.RenameField(
            model_name="consumedcalories",
            old_name="protein",
            new_name="proteins",
        ),
        migrations.RenameField(
            model_name="usernutritiongoal",
            old_name="fat_goal",
            new_name="fats_goal",
        ),
        migrations.RenameField(
            model_name="usernutritiongoal",
            old_name="protein_goal",
            new_name="proteins_goal",
        ),
    ]
