# Generated by Django 5.1.3 on 2025-03-28 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_rename_exp_profile_points_remove_task_exp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_message",
                    models.TextField(verbose_name="Сообщение пользователя"),
                ),
                ("ai_response", models.TextField(verbose_name="Ответ ИИ (Системы)")),
                (
                    "prompt_sent",
                    models.TextField(
                        blank=True, null=True, verbose_name="Промпт, отправленный ИИ"
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Определенный сценарий",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время обмена"
                    ),
                ),
                (
                    "error_occurred",
                    models.BooleanField(default=False, verbose_name="Произошла ошибка"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь (Игрок)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории чата",
                "verbose_name_plural": "История чата",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название квеста"),
                ),
                ("description", models.TextField(verbose_name="Описание/Цели")),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Ежедневный"),
                            ("URGENT", "Срочный"),
                            ("MAIN", "Основной"),
                            ("CHALLENGE", "Челлендж"),
                        ],
                        default="CHALLENGE",
                        max_length=20,
                        verbose_name="Тип квеста",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Активен"),
                            ("COMPLETED", "Выполнен"),
                            ("FAILED", "Провален"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "reward_points",
                    models.IntegerField(default=0, verbose_name="Награда XP"),
                ),
                (
                    "reward_other",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Другая награда (текст)",
                    ),
                ),
                (
                    "penalty_info",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Штраф (текст)",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время генерации",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Срок выполнения (для срочных)",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время выполнения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Квест (от ИИ)",
                "verbose_name_plural": "Квесты (от ИИ)",
                "ordering": ["-generated_at"],
            },
        ),
    ]
