# Generated by Django 5.1.3 on 2025-04-08 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_userhabit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userhabit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Привычка пользователя",
                "verbose_name_plural": "Привычки пользователей",
            },
        ),
        migrations.AddField(
            model_name="userhabit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Daily", "Ежедневно"),
                    ("Weekly", "Еженедельно"),
                    ("Monthly", "Ежемесячно"),
                ],
                default="Daily",
                max_length=20,
                verbose_name="Частота",
            ),
        ),
        migrations.AddField(
            model_name="userhabit",
            name="icon",
            field=models.CharField(
                blank=True,
                default="list-ul",
                max_length=50,
                null=True,
                verbose_name="Иконка",
            ),
        ),
        migrations.AddField(
            model_name="userhabit",
            name="notification_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Уведомления включены"
            ),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, если привычка активна (используется для мягкого удаления)",
                verbose_name="Активна",
            ),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="last_tracked",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последней отметки"
            ),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Текущий стрик (дней)"
            ),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название привычки"),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="userhabit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
