from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes),
    path('register/', views.registerAccount),
    path('login/', views.loginUser),
    path('logout/', views.logoutUser),
    path('profile/', views.userProfile),
    path('tasks/', views.tasksView),
    path('tasks/create/', views.createTask),
    path('tasks/complete/<int:pk>/', views.completeTask, name='complete-task'),
    path('tasks/<str:pk>/', views.getTask),
    path('tasks/<str:pk>/update/', views.updateTask),
    path('tasks/<str:pk>/delete/', views.deleteTask),
    path('send_friend_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:user_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('reject_friend_request/<int:user_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('sendMessage/', views.sendMessage, name='sendMessage'),
    path('getMessages/', views.getMessages, name='getMessages'),
    path('notifications/', views.getNotifications, name='getNotifications'),
    path('groups/', views.listGroups, name='listGroups'),
    path('groups/create/', views.createGroup, name='createGroup'),
    path('groups/<int:group_id>/join/', views.joinGroup, name='joinGroup'),
    path('groups/<int:group_id>/leave/', views.leaveGroup, name='leaveGroup'),
    path('groups/<int:group_id>/messages/', views.getGroupMessages, name='getGroupMessages'),
    path('groups/<int:group_id>/messages/send/', views.sendGroupMessage, name='sendGroupMessage'),
    path('pomodoro/start/', views.start_pomodoro_session, name='start_pomodoro_sessions'),
    path('pomodoro/<int:pk>/update/', views.update_pomodoro_session, name='update_pomodoro_sessions'),
    path('pomodoro/<int:pk>/delete/', views.delete_pomodoro_session, name='delete_pomodoro_sessions'),
    path('pomodoro/', views.get_pomodoro_sessions, name='get_pomodoro_sessions'),
    path('educational-content/', views.get_educational_content, name='get_educational_content'),
    path('educational-content/<int:content_id>/', views.view_educational_content, name='view_educational_content'),
    path('educational-content/add/', views.add_educational_content, name='add_educational_content'),
    path('educational-content/<int:content_id>/delete/', views.delete_educational_content, name='delete_educational_content'),
    path('educational-content/<int:content_id>/update/', views.update_educational_content, name='update_educational_content'),
]